services:
  nginx:
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/prod/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

  backend:
    environment:
      REZEPTE_TEST: '0'
      WEBAUTHN_RP_ID: ${WEBAUTHN_RP_ID:-rezepte.unbenet.de}

  certbot:
    image: certbot/certbot:latest
    profiles:
      - tools
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
